# Your project's server will run on localhost:xxxx at this port
PORT: 8000

# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 9"
  - "ios >= 7"

# UnCSS will use these settings
UNCSS_OPTIONS:
  html:
    # Search for used CSS classes in generated HTML files
    - "dist/**/*.html"
  ignore:

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: "dist"
  # Paths to static assets
  imageAssets: "src/assets/**/*.{ico,jpg,png,svg}"
  miscAssets:
    - "src/**/*"
    - "!src/{img,js,scss,ts,hbs}/**/*"
  # Paths to Sass libraries, which can then be loaded with @import
  sass:
  # Paths to JavaScript entry points for webpack to bundle modules
  src: "src"
  components: "src/components"
  data: "src/data"
  layouts: "src/layouts"
  pageTemplates:  "src/pages"
  styleGuide: "src/styleguide"
  partials: "src/components"